name: Build, Sign, and Publish Firefox Extension

on:
  push:
    branches:
      - main

jobs:
  build-sign-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install web-ext tool
        run: npm install -g web-ext

      - name: Build and Sign Extension
        run: |
          cd extension
          web-ext sign --api-key=${{ secrets.AMO_JWT_ISSUER }} --api-secret=${{ secrets.AMO_JWT_SECRET }} --timeout 300

      - name: Prepare GitHub Pages Deployment
        run: |
          mkdir -p docs
          cp extension/web-ext-artifacts/*.xpi docs/atjfr.xpi
          
          LATEST_VERSION=$(ls extension/web-ext-artifacts/*.xpi | grep -o '[0-9]\+\.[0-9]\+' | head -1)
          
          echo '{
            "addons": {
              "atjfr-ff@barraud.io": {
                "updates": [
                  {
                    "version": "'$LATEST_VERSION'",
                    "update_link": "https://jwtools.github.io/atjfr/atjfr.xpi"
                  }
                ]
              }
            }
          }' > docs/updates.json

          # Générer une page HTML avec un lien vers la dernière version
          echo '<!DOCTYPE html>
          <html lang="fr">
          <head>
              <meta charset="UTF-8">
              <meta name="viewport" content="width=device-width, initial-scale=1.0">
              <title>Extension Firefox Privée</title>
          </head>
          <body>
              <h1>Extension Firefox Privée</h1>
              <p>Dernière version : <strong>'$LATEST_VERSION'</strong></p>
              <p><a href="extension.xpi" download="atjfr.xpi">📥 Télécharger l’extension</a></p>
              <p>Pour l’installer, ouvrez <code>about:addons</code> dans Firefox et sélectionnez le fichier téléchargé.</p>
          </body>
          </html>' > docs/index.html

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: main
          folder: docs
